# - Configuration file stored 2023-11-24 11:46:57.988160 - 
AppSettings: #!!python/object:controller.AppSettings
 ENABLE_CUSTOM_TITLE_BAR: True # ENABLE_CUSTOM_TITLE_BAR: None
 MENU_WIDTH: 240 # MENU_WIDTH: None
 LEFT_BOX_WIDTH: 240 # LEFT_BOX_WIDTH: None
 RIGHT_BOX_WIDTH: 240 # RIGHT_BOX_WIDTH: None
 TIME_ANIMATION: 500 # TIME_ANIMATION: None
 BTN_LEFT_BOX_COLOR: "background-color: rgb(44, 49, 58);" # BTN_LEFT_BOX_COLOR: None
 BTN_RIGHT_BOX_COLOR: "background-color: #ff79c6;" # BTN_RIGHT_BOX_COLOR: None
 MENU_SELECTED_STYLESHEET: "
           border-left: 22px solid qlineargradient(spread:pad, x1:0.034, y1:0, x2:0.216, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));
           background-color: rgb(40, 44, 52);
           " # MENU_SELECTED_STYLESHEET: None
