# - Configuration file stored 2023-11-24 11:46:57.990884 - 
CaptDeviceConfig: #!!python/object:controller.CaptDeviceConfig
 sample_rate: 50000 # Sample rate: Sample rate of the device
 streaming_rate: 500 # Streaming rate: Streaming rate in Hz (should be below 1kHz)
 ain_channel: 0 # Analog In Channel: Analog in channel. Defines which channel is used for capturing.
 show_simulator: True # Show Simulators: Show available simulators in the device list provided by the DreamWaves API.
 streaming_history: 2000 # Streaming history (ms): Defines the range of the stream in ms
 total_samples: 200000 # total_samples: None
 sample_time: 45 # sample_time: None
 ad2_raw_out_file: "{output_directory}/measurement/ad2_raw/ad2_out_{wafer_nr}_{date}.csv" # ad2_raw_out_file: None
